query RepositoryDetails($owner: String!, $name: String!) {
    repository(owner: $owner, name: $name) {
        readmeUpper: object(expression: "HEAD:README.md") {
            ... on Blob { text }
        }
        readmeLower: object(expression: "HEAD:readme.md") {
            ... on Blob { text }
        }
        readmeAllCaps: object(expression: "HEAD:README.MD") {
            ... on Blob { text }
        }
        readmeMixed: object(expression: "HEAD:Readme.md") {
            ... on Blob { text }
        }
        readmeNoExt: object(expression: "HEAD:README") {
            ... on Blob { text }
        }
        readmeRst: object(expression: "HEAD:README.rst") {
            ... on Blob { text }
        }
    }
}
