query SearchRepositories($query: String!, $first: Int!) {
    search(query: $query, type: REPOSITORY, first: $first) {
        repositoryCount
        nodes {
            ... on Repository {
                id
                name
                nameWithOwner
                description
                url
                stargazerCount
                forkCount
                primaryLanguage {
                    name
                    color
                }
                owner {
                    login
                    avatarUrl
                }
            }
        }
    }
}
