query SearchRepositories($query: String!, $first: Int!, $after: String) {
    search(query: $query, type: REPOSITORY, first: $first, after: $after) {
        repositoryCount
        pageInfo {
            endCursor
            hasNextPage
        }
        nodes {
            ... on Repository {
                id
                name
                nameWithOwner
                description
                url
                stargazerCount
                forkCount
                createdAt
                updatedAt
                primaryLanguage {
                    name
                    color
                }
                owner {
                    __typename
                    login
                    avatarUrl
                }
                repositoryTopics(first: 10) {
                    nodes {
                        topic {
                            name
                        }
                    }
                }
            }
        }
    }
}
